Isotope Rewrite
Slimefun-Addon-Community/SlimeChem pull request #2
Opened 2020-12-24 02:40 UTC by Seggan

I rewrote the isotope system to use a JSON file that contains the isotope data. I'm making a PR to see what you guys think I need to change before I merge. @Mooy1 pls don't merge this

2020-12-24 03:01 UTC, WalshyDev requested changes
Just a quick pass through

2020-12-24 03:01 UTC, WalshyDev commented on pom.xml
> +                            <pattern>org.json</pattern>
You shouldn't really use Simple JSON, it's terrible performance and kinda usage wise. Plus, GSON is already included in Bukkit. May as well just use that.

2020-12-24 03:01 UTC, WalshyDev commented on pom.xml
> +        <finalName>${project.name} v${project.version}</finalName>
I don't see much point editing this to begin with but either way, I wouldn't be prefixing it with v when it's probably on the build repo so it'll be vDEV - xxx

2020-12-24 03:01 UTC, WalshyDev commented on pom.xml
> +    <build>
Oh I see you moved this whole block. Not sure why. I always hate build being up before deps. It just makes no sense to me at all + it's a huge block of crap. Deps and repos are small and edited more often. Plus, logically order wise it makes sense to do repos, deps and the build but dealers choice.

2020-12-24 03:01 UTC, WalshyDev commented on src/main/java/io/github/mooy1/slimechem/implementation/atomic/Element.java
> +        return (number > 82 && number < 121) || this == TECHNETIUM || this == PROMETHIUM;
This should really just be a property for futures sake but that's my opinion.

2020-12-24 03:01 UTC, WalshyDev commented on src/main/java/io/github/mooy1/slimechem/implementation/atomic/isotopes/DecayType.java
> +    ALPHA("alpha"),
Empty line after class open and content pls

2020-12-24 03:01 UTC, WalshyDev commented on src/main/java/io/github/mooy1/slimechem/implementation/atomic/isotopes/DecayType.java
> +    public static DecayType getByRepresentation(String representation) {
If you intend to call this method a lot you may want to speed it up by making a static `values` the `values()` method copies the array every single call. You could also make a lookup map which would speed it up to O(1) rather than O(n)

2020-12-24 03:01 UTC, WalshyDev commented on src/main/java/io/github/mooy1/slimechem/implementation/atomic/isotopes/Isotope.java
> +        formula = SuperNum.fromInt(mass) + abbr;
this. Missing from some of these. Be consistent!

2020-12-24 03:01 UTC, WalshyDev commented on src/main/java/io/github/mooy1/slimechem/implementation/atomic/isotopes/Isotope.java
> +        if (isotopes.containsKey(element)) {
Never do containsKey! It's a useless lookup!

you can do a compute

2020-12-24 03:01 UTC, WalshyDev commented on src/main/java/io/github/mooy1/slimechem/lists/Constants.java
> +public class Constants {
Class should be final and have a private constructor

2020-12-24 03:01 UTC, WalshyDev commented on src/main/java/io/github/mooy1/slimechem/setup/Registry.java
> +                List<Isotope> superIsotopes = new ArrayList<>();
Can't this be a set?

2020-12-24 03:01 UTC, WalshyDev commented on src/main/java/io/github/mooy1/slimechem/setup/Registry.java
> +                    for (Isotope iso : isotopes.get(el)) {
entrySet. You're wasting time doing another lookup

2020-12-24 16:28 UTC, Seggan commented on pom.xml
> +    <build>
I always put my build before deps

2020-12-24 17:56 UTC, Seggan commented on src/main/java/io/github/mooy1/slimechem/setup/Registry.java
> +                List<Isotope> superIsotopes = new ArrayList<>();
I use list for ordering and the `Util.trimList` method

2020-12-26 15:13 UTC, Seggan commented on pom.xml
> +        <finalName>${project.name} v${project.version}</finalName>
That was mooy

2020-12-26 21:56 UTC, Mooy1 commented on pom.xml
> +        <finalName>${project.name} v${project.version}</finalName>
its part of addon template afaik

2020-12-31 20:35 UTC, merged